// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Recoil from "recoil";
import * as AppFamily from "./AppFamily.js";
import * as ReactDom from "react-dom";
import * as AppSnapshot from "./AppSnapshot.js";
import * as AppTodoList from "./AppTodoList.js";
import * as Recoil_Logger from "../src/Recoil_Logger.js";
import * as AppPersistence from "./AppPersistence.js";

var root = document.querySelector("#app");

if (!(root == null)) {
  ReactDom.render(React.createElement(Recoil.RecoilRoot, {
            children: null
          }, React.createElement(Recoil_Logger.make, {
                collapsed: false
              }), React.createElement("h1", undefined, "Todo"), React.createElement(AppTodoList.make, {}), React.createElement("h1", undefined, "Family"), React.createElement(AppFamily.make, {}), React.createElement("h1", undefined, "Persistence"), "Open the console to see messages", React.createElement(AppPersistence.make, {}), React.createElement("h1", undefined, "Snapshot"), React.createElement(AppSnapshot.make, {})), root);
}

export {
  
}
/* root Not a pure module */
