// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Recoil from "recoil";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";

var atom = Recoil.atom({
      key: "Persistence",
      default: "",
      persistence_UNSTABLE: "log"
    });

function AppPersistence$Item(Props) {
  var item = Props.item;
  var match = Recoil.useRecoilState(atom);
  var setSelected = match[1];
  return React.createElement("li", {
              className: match[0] === item ? "bg-red" : "bg-white",
              onClick: (function (_e) {
                  return setSelected(function (param) {
                              return item;
                            });
                })
            }, item);
}

var Item = {
  make: AppPersistence$Item
};

function AppPersistence(Props) {
  return React.createElement("div", undefined, React.createElement("ul", undefined, Belt_Array.map([
                      "custom1",
                      "custom2",
                      "custom3",
                      "custom4"
                    ], (function (item) {
                        return React.createElement(AppPersistence$Item, {
                                    item: item,
                                    key: item
                                  });
                      }))));
}

var make = AppPersistence;

export {
  atom ,
  Item ,
  make ,
  
}
/* atom Not a pure module */
