// Generated by ReScript, PLEASE EDIT WITH CARE


var Family = {};

var Atom = {
  Family: Family
};

var Props = {};

var Family$1 = {};

var Selector = {
  Props: Props,
  Family: Family$1
};

function classify(loadable) {
  var state = loadable.state;
  switch (state) {
    case "hasValue" :
        return {
                TAG: /* HasValue */0,
                _0: loadable.contents
              };
    case "loading" :
        return /* Loading */0;
    default:
      return {
              TAG: /* Error */1,
              _0: loadable.contents
            };
  }
}

var Loadable = {
  classify: classify
};

function get(snap, atom) {
  return classify(snap.getLoadable(atom));
}

var Snapshot = {
  get: get
};

var Callback = {};

var Root;

var Observer;

var Logger;

export {
  Atom ,
  Selector ,
  Loadable ,
  Snapshot ,
  Callback ,
  Root ,
  Observer ,
  Logger ,
  
}
/* No side effect */
