// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Recoil = require("recoil");
var AppFamily = require("./AppFamily.js");
var ReactDOMRe = require("reason-react/lib/js/src/legacy/ReactDOMRe.bs.js");
var AppSnapshot = require("./AppSnapshot.js");
var AppTodoList = require("./AppTodoList.js");
var Recoil_Logger = require("../src/Recoil_Logger.js");
var AppPersistence = require("./AppPersistence.js");

ReactDOMRe.renderToElementWithId(React.createElement(Recoil.RecoilRoot, {
          children: null
        }, React.createElement(Recoil_Logger.make, {
              collapsed: false
            }), React.createElement("h1", undefined, "Todo"), React.createElement(AppTodoList.make, {}), React.createElement("h1", undefined, "Family"), React.createElement(AppFamily.make, {}), React.createElement("h1", undefined, "Persistence"), "Open the console to see messages", React.createElement(AppPersistence.make, {}), React.createElement("h1", undefined, "Snapshot"), React.createElement(AppSnapshot.make, {})), "app");

/*  Not a pure module */
