// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Recoil = require("recoil");
var AppFamily = require("./AppFamily.js");
var ReactDom = require("react-dom");
var AppSnapshot = require("./AppSnapshot.js");
var AppTodoList = require("./AppTodoList.js");
var Recoil_Logger = require("../src/Recoil_Logger.js");
var AppPersistence = require("./AppPersistence.js");

var root = document.querySelector("app");

if (!(root == null)) {
  ReactDom.render(React.createElement(Recoil.RecoilRoot, {
            children: null
          }, React.createElement(Recoil_Logger.make, {
                collapsed: false
              }), React.createElement("h1", undefined, "Todo"), React.createElement(AppTodoList.make, {}), React.createElement("h1", undefined, "Family"), React.createElement(AppFamily.make, {}), React.createElement("h1", undefined, "Persistence"), "Open the console to see messages", React.createElement(AppPersistence.make, {}), React.createElement("h1", undefined, "Snapshot"), React.createElement(AppSnapshot.make, {})), root);
}

/* root Not a pure module */
